name: "Close stale issues"
on:
  schedule:
    - cron: "0 0 * * 0" # weekly
  workflow_dispatch:
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale..."
          days-before-stale: 30
          days-before-close: 7
